name: CD - Deploy de Artefatos

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Login no Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build e Push da Imagem Docker
      run: |
        docker build -t meu_usuario/converter:latest .
        docker tag meu_usuario/converter:latest meu_usuario/converter:${{ github.ref_name }}
        docker push meu_usuario/converter:latest
        docker push meu_usuario/converter:${{ github.ref_name }}
