name: CI - Teste e Artefatos

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Executar testes
      run: |
        pytest --maxfail=1 --disable-warnings --junitxml=relatorio_testes.xml

    - name: Criar artefato de exemplo
      run: |
        echo "Versão do Projeto: 1.0.0" > versao.txt
        echo "Build gerado com sucesso." >> versao.txt

    - name: Fazer upload dos artefatos
      uses: actions/upload-artifact@v3
      with:
        name: artefatos-build
        path: |
          relatorio_testes.xml
          versao.txt
